PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE plantas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    informacion TEXT,
    categoria TEXT
);
INSERT INTO plantas VALUES(1,'Sida abutifolia','Una planta herbácea común en áreas tropicales y subtropicales, conocida por sus pequeñas flores amarillas y su uso medicinal en algunas culturas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(2,'Lysiloma acapulcensis','Un árbol que se encuentra en áreas tropicales de México. Es usado en reforestación y su madera en carpintería.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(3,'Acacia acatlensis','Esta acacia es nativa de México y crece en zonas áridas y semiáridas. Su nombre común se debe a que se utiliza para forraje de animales','DICOTYLEDONAE');
INSERT INTO plantas VALUES(4,'Lantana achyranthifolia','Una planta arbustiva con flores coloridas, generalmente de color rosa, amarillo o rojo. Es resistente y crece en áreas secas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(5,'Plumería acutifolia','Es famosa por sus flores fragantes y atractivas, comúnmente vistas en jardines. En algunas culturas, sus flores se usan en coronas o collares.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(6,'Ceiba aesculifolia','Este árbol de gran tamaño es característico por sus espinas en el tronco. Sus fibras se usan tradicionalmente para hacer rellenos de almohadas','DICOTYLEDONAE');
INSERT INTO plantas VALUES(7,'Conopholis alpina','Planta parasitaria que se encuentra en áreas montañosas, alimentándose de las raíces de otras plantas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(8,'Chenopodiu m ambrosioides','Mejor conocida como epazote, es utilizada principalmente como hierba medicinal y condimento en la cocina mexicana','DICOTYLEDONAE');
INSERT INTO plantas VALUES(9,'Solanum americanum','Un arbusto que produce pequeñas bayas negras. Algunas partes de la planta pueden ser tóxicas si se consumen en grandes cantidades.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(10,'Simsia amplexicaulis','Es una planta de la familia de las margaritas, común en terrenos baldíos o zonas perturbadas. Sus flores amarillas y hojas abrazadoras son características','DICOTYLEDONAE');
INSERT INTO plantas VALUES(11,'Pseudosmo dingium andreux','Un árbol conocido por sus propiedades medicinales y su uso en la reforestación de zonas áridas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(12,'Agave angustifolia','Es el maguey más comúnmente usado en la producción de mezcal. También se utiliza en medicina tradicional y como planta ornamental.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(13,'Malvaviscus arboreus','Un arbusto con flores rojas brillantes, usado tradicionalmente en el tratamiento de problemas respiratorios','DICOTYLEDONAE');
INSERT INTO plantas VALUES(14,'Anagallis arvensis','Planta herbácea de pequeñas flores rojas o azules, empleada en la medicina popular para tratar infecciones','DICOTYLEDONAE');
INSERT INTO plantas VALUES(15,'Bidens aurea','Planta con propiedades medicinales, usada principalmente para problemas digestivos. Sus flores amarillas son llamativas','DICOTYLEDONAE');
INSERT INTO plantas VALUES(16,'Dalea bicolor','Planta de la familia Fabaceae, con flores coloridas que atraen a polinizadores, usada ornamentalmente en zonas áridas','DICOTYLEDONAE');
INSERT INTO plantas VALUES(17,'Acacia bilimekii','Conocida como "Mushel espinoso", esta acacia se usa en cercos vivos y reforestación. Crece en climas semiáridos','DICOTYLEDONAE');
INSERT INTO plantas VALUES(18,'Glandularia bipinnatifida','Planta con flores purpúreas o rosadas, nativa de áreas áridas y comúnmente llamada "Alfombrilla de campo"','DICOTYLEDONAE');
INSERT INTO plantas VALUES(19,'Cosmos bipinnatus','Conocido como "Girasol morado", es una planta ornamental que atrae polinizadores y se adapta bien a suelos pobres​','DICOTYLEDONAE');
INSERT INTO plantas VALUES(20,'Salix bonplandiana','También llamado "Sauce llorón", se usa en reforestación y control de erosión en zonas ribereñas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(21,'Psilactis  brevilingulata','Es una planta con flores de tonos violetas, generalmente se encuentra en áreas desérticas. Tiene propiedades medicinales','DICOTYLEDONAE');
INSERT INTO plantas VALUES(22,'Cologania broussoneti','Es una planta perenne que se desarrolla en climas templados. Pertenece a la familia de las leguminosas, y sus flores suelen ser rosadas o moradas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(23,'Psittacanthu s calyculatus','Un muérdago que se encuentra comúnmente en árboles como encinos y pinos, produciendo flores rojas. Es una planta hemiparásita.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(24,'Lantana camara','Conocida por sus flores de colores vibrantes, es una planta invasora en algunas regiones. También se usa en medicina tradicional.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(25,'Conyza canadensis','Una planta herbácea que se caracteriza por sus pequeños capítulos florales. Es considerada maleza en muchos cultivos','DICOTYLEDONAE');
INSERT INTO plantas VALUES(26,'Sideroxylon capiri','Árbol conocido como tempisque, puede alcanzar los 35 metros. Sus frutos en forma de baya son comestibles cuando están maduros​','DICOTYLEDONAE');
INSERT INTO plantas VALUES(27,'Prunus capuli','El capulín es un árbol frutal, cuyas bayas oscuras son comestibles y utilizadas en gastronomía.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(28,'Alternanther a caracasana','Planta herbácea con propiedades medicinales, usada comúnmente en remedios para tratar infecciones.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(29,'Eryngium carlinae','Conocida como cardo, esta planta de flores espinosas es común en áreas montañosas. Tiene uso ornamental y medicinal.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(30,'Quercus castanea','Un tipo de encino que crece en zonas templadas, apreciado por su madera dura.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(31,'Celtis caudata','Árbol o arbusto conocido por su madera resistente. Crece en diversas regiones de México, preferentemente en climas cálidos y secos.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(32,'Lepechinia caulescens','Planta aromática de la familia de las Lamiaceae. Se encuentra en bosques montañosos de México y se usa tradicionalmente en infusiones','DICOTYLEDONAE');
INSERT INTO plantas VALUES(33,'Annona cherimola','Fruto tropical de sabor dulce, originario de América, especialmente cultivado en climas cálidos. Es valorada por su pulpa comestible.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(34,'Rhus chondroloma','Planta del género Rhus, caracterizada por sus hojas compuestas y su presencia en zonas áridas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(35,'Erodium cicutarium','Conocido como "alfilerillo", es una hierba común en campos y pastizales. Tiene pequeñas flores de color púrpura o rosa.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(36,'Boerhavia coccinea','Planta rastrera que crece en suelos secos. Sus flores rosadas y su capacidad de resistir climas extremos la hacen distintiva','DICOTYLEDONAE');
INSERT INTO plantas VALUES(37,'Phaseolus coccineus','Especie de frijol de flores rojas, común en regiones altas de México, utilizado tanto para alimento como para forraje.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(38,'Acacia cochliacantha','Arbusto espinoso que crece en zonas secas de México. Sus semillas se utilizan a veces en la medicina tradicional','DICOTYLEDONAE');
INSERT INTO plantas VALUES(39,'Baccharis conferta','Arbusto perenne que se encuentra en zonas montañosas de México. Sus flores amarillas lo hacen fácil de identificar.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(40,'Melochia corymbosa','Planta que crece en suelos húmedos y se reconoce por sus pequeñas flores en racimos.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(41,'Ageratum corymbosum','Planta herbácea nativa, común en áreas perturbadas. Se usa para controlar la erosión y a veces en medicina tradicional para tratar heridas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(42,'Ficus cotinifolia','Árbol que puede alcanzar hasta 30 metros de altura. Tiene raíces aéreas características y es importante en la regeneración de ecosistemas, además de tener uso ornamental.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(43,'Rumex crispus','Planta herbácea conocida por sus hojas alargadas y uso medicinal. Es nativa de Eurasia pero también se encuentra en México. Ayuda a tratar trastornos digestivos','DICOTYLEDONAE');
INSERT INTO plantas VALUES(44,'Asclepias curassavica','Conocida como "hierba de la golondrina", esta planta tiene flores de colores brillantes y es vital para las mariposas monarca. Se utiliza en medicina tradicional para tratar infecciones','DICOTYLEDONAE');
INSERT INTO plantas VALUES(45,'Krameria cytisoides','Arbusto que crece en zonas áridas de México. Sus raíces son empleadas en medicina tradicional, especialmente para tratar problemas digestivos.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(46,'Lamourouxi a dasyantha','Planta herbácea con flores rojas tubulares, atractiva para colibríes. Crece en bosques húmedos y tiene un papel importante en la biodiversidad local.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(47,'Gomphrena decumbens','Planta pequeña con flores violetas, común en zonas áridas. Se utiliza como ornamental y también tiene propiedades medicinales.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(48,'Amelanchier denticulata','Arbusto que crece en zonas templadas. Sus frutos comestibles son apreciados por la fauna local.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(49,'Clematis dioica','Planta trepadora que produce flores grandes y blancas. Es utilizada como ornamental y también en medicina popular para tratar dolores de cabeza.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(50,'Croton dioicus','Arbusto conocido en la medicina tradicional por sus propiedades como abortivo. También se usa para tratar problemas respiratorios.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(51,'Bauhinia dipetala','Árbol pequeño conocido como "pata de vaca" por la forma de sus hojas. Se usa en la medicina tradicional y es ornamental','DICOTYLEDONAE');
INSERT INTO plantas VALUES(52,'Mascagnia dipholiphylla','Planta trepadora nativa de México, conocida por sus vistosas flores amarillas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(53,'Casimiroa edulis','Árbol frutal cuyas frutas son comestibles. También se utiliza en la medicina tradicional para tratar la ansiedad y el insomnio.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(54,'Echinoptery s eglandulosa','Planta trepadora que crece en climas cálidos y secos. Produce flores pequeñas y poco llamativas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(55,'Roldana ehrenbergiana','Planta medicinal usada para problemas respiratorios y como diurético','DICOTYLEDONAE');
INSERT INTO plantas VALUES(56,'Bouvardia erecta','Arbusto ornamental de flores rojas que se utiliza para atraer colibríes y otros polinizadores.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(57,'Leucaena esculenta','Árbol cuyo fruto, el guaje, es comestible. Tiene importancia económica y ecológica en México.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(58,'Ageratina espinosarum','Arbusto usado en la medicina tradicional para aliviar problemas gastrointestinales','DICOTYLEDONAE');
INSERT INTO plantas VALUES(59,'Acacia farnesiana','Árbol de flores amarillas con fragancia dulce, utilizado en perfumería y medicina tradicional.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(60,'Harpalyce formosa','Arbusto que se encuentra en México y es conocido por sus propiedades medicinales.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(61,'Cercocarpus fothergilloides','Este arbusto o pequeño árbol se encuentra en bosques templados. Sus hojas son perennes y tiene importancia ecológica para la fauna local.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(62,'Quercus frutex','Un encino de tamaño pequeño que se adapta bien a condiciones áridas y se encuentra en zonas montañosas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(63,'Bursera galeottiana','Árbol de la familia de las burseráceas que crece en zonas secas. Se le conoce por su corteza aromática y su uso en la medicina tradicional.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(64,'Echeveria gibbiflora','Planta suculenta nativa de México, valorada tanto ornamentalmente por su roseta de hojas carnosas como por su resistencia a la sequía.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(65,'Asclepias glaucescens','Esta especie de la familia de las Asclepiadaceae es conocida por sus flores atractivas y es una planta esencial para la reproducción de las mariposas monarca.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(66,'Quercus glaucoides','Encino de hojas perennes, que es común en bosques templados de México y desempeña un papel crucial en la conservación del suelo.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(67,'Helianthemu m glomeratum','Planta de flores pequeñas y amarillas que crece en zonas áridas, conocida por su capacidad para adaptarse a suelos rocosos.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(68,'Flourensia glutinosa','También conocida como “incayuyo”, esta planta tiene usos medicinales, principalmente en infusiones para tratar problemas respiratorios.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(69,'Gymnosper ma glutinosum','Arbusto que se utiliza en la medicina tradicional para tratar dolores y malestares gástricos.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(70,'Machaonia hahniana','Arbusto que habita en zonas secas de México, reconocible por sus flores blancas y su uso en la reforestación de áreas áridas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(71,'Cardiosperm um halicacabum','Es una planta trepadora conocida como "globo". Se usa tradicionalmente para tratar afecciones como inflamaciones y dolores articulares.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(72,'Senna holwayana','Planta con flores amarillas de la familia Fabaceae, usada en medicina tradicional y común en áreas de matorrales','DICOTYLEDONAE');
INSERT INTO plantas VALUES(73,'Karwinskia humboldtiana','Arbusto tóxico conocido como "tullidora". Sus frutos pueden causar parálisis si se ingieren','DICOTYLEDONAE');
INSERT INTO plantas VALUES(74,'Arachis hypogaea','Planta que produce los cacahuates. Es ampliamente cultivada por sus semillas comestibles.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(75,'Gochnatia hypoleuca','Arbusto con flores amarillas, característico de zonas semiáridas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(76,'Phytolacca icosandra','Conocida como "hierba carmín", es tóxica en grandes cantidades, pero se usa medicinalmente para tratar inflamaciones','DICOTYLEDONAE');
INSERT INTO plantas VALUES(77,'Capparis incana','Arbusto común en zonas áridas, apreciado por sus frutos.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(78,'Melilotus indicus','Planta utilizada para forraje y en medicina natural.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(79,'Brongniartia intermedia','Planta leguminosa común en climas cálidos y secos.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(80,'Grindelia inuloides','Utilizada en medicina tradicional para tratar problemas respiratorios y de la piel.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(81,'Mirabilis jalapa','Una planta ornamental con flores coloridas, conocida por abrir sus flores por la tarde. Es común en zonas tropicales y subtropicales.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(82,'Erigeron karvinskianus','Es una planta perenne que crece en suelos secos y soleados. Es popular por sus pequeñas flores blancas y rosadas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(83,'Mimosa lacerata','Una especie dentro del género Mimosa, generalmente conocida por sus hojas sensibles que se cierran al tocarlas. Crece en zonas cálidas y áridas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(84,'Quercus laeta','Es un roble característico de zonas montañosas en México, sus hojas tienen un color verde brillante y proporciona madera útil.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(85,'Prosopis laevigata','Un árbol característico de zonas áridas y semiáridas en México, importante por su capacidad para fijar nitrógeno en el suelo','DICOTYLEDONAE');
INSERT INTO plantas VALUES(86,'Solanum lanceolatum','Arbusto que pertenece al género Solanum, crece en zonas tropicales y tiene propiedades medicinales.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(87,'Quercus laurina','Un roble que crece en áreas montañosas, se distingue por sus hojas alargadas y sus usos en carpintería y construcción','DICOTYLEDONAE');
INSERT INTO plantas VALUES(88,'Lobelia laxiflora','Planta conocida por sus flores tubulares de color rojo o naranja brillante, que atrae colibríes.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(89,'Asclepias linaria','Planta perenne que sirve de alimento para las mariposas monarca en su etapa de larva, característica por sus hojas lineales.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(90,'Bunchosia lindeniana','Arbusto pequeño que produce frutos amarillos o rojos comestibles, generalmente usado en la medicina tradicional.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(91,'Artemisia ludoviciana','Esta planta pertenece a la familia Asteraceae. Es conocida por sus usos medicinales y en la elaboración de infusiones. Se encuentra comúnmente en pastizales y áreas perturbadas.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(92,'Medicago lupulina','Conocida como trébol negro, es una leguminosa forrajera que se utiliza en la alimentación del ganado. Se caracteriza por su habilidad para fijar nitrógeno en el suelo, mejorando la fertilidad del mismo','DICOTYLEDONAE');
INSERT INTO plantas VALUES(93,'Porophyllum macrocephalum','Esta planta se encuentra en diversas regiones de México. Se utiliza en medicina tradicional y tiene propiedades antimicrobianas. Su uso es más común en prácticas de curación local.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(94,'Dahlia merckii','Esta dahlia es una planta ornamental, conocida por sus flores coloridas y su importancia en el paisajismo. Crece en climas templados y se cultiva por su belleza visual.','DICOTYLEDONAE');
INSERT INTO plantas VALUES(95,'Asclepias mexicana','Es una especie de planta que sirve como fuente de alimento para las larvas de mariposas, especialmente las monarcas. Tiene propiedades medicinales y es valorada en la medicina tradicional','DICOTYLEDONAE');
INSERT INTO plantas VALUES(96,'Achillea millefolium','Usada en medicina herbal, esta planta es conocida por sus propiedades antiinflamatorias y analgésicas. Se encuentra en diversas zonas templadas y es un componente popular en remedios naturales','DICOTYLEDONAE');
INSERT INTO plantas VALUES(97,'Schinus molle','Este árbol es apreciado por su sombra y se utiliza en la medicina tradicional para diversos tratamientos. También se cultiva por su resina, que tiene aplicaciones aromáticas','DICOTYLEDONAE');
INSERT INTO plantas VALUES(98,'Pinguicula moranensis','Esta planta carnívora es nativa de México y se caracteriza por su capacidad para atrapar insectos. Se cultiva principalmente como planta ornamental y tiene aplicaciones en la medicina tradicional','DICOTYLEDONAE');
INSERT INTO plantas VALUES(99,'Lamourouxi a multifida','Es una planta endémica que se encuentra en regiones específicas de México. Se destaca por sus características botánicas únicas y su uso en estudios de conservación','DICOTYLEDONAE');
INSERT INTO plantas VALUES(100,'Senna multiglandulosa','Esta especie de Senna se utiliza en medicina tradicional, especialmente por sus propiedades laxantes. Es una planta que prospera en climas cálidos y secos​','DICOTYLEDONAE');
INSERT INTO sqlite_sequence VALUES('plantas',100);
COMMIT;
